@Test public void constructor_PassesCause(){
  Exception cause=new Exception();
  ValidationException exception=new ValidationException(cause);
  assertThat(exception).hasCause(cause);
}
