@Test public void should_honor_custom_error_message_set_with_withFailMessage(){
  String error="ssss";
  assertThatExceptionOfType(AssertionError.class).isThrownBy(() -> assertThat(new AtomicLong(0)).withFailMessage(error).hasValueLessThan(-1)).withMessageContaining(error);
}
