@Test public void should_fail_when_predicate_accepts_value(){
  DoublePredicate predicate=val -> val <= 2;
  Predicate<Double> wrapPredicate=predicate::test;
  double expectedValue=2.0;
  assertThatExceptionOfType(AssertionError.class).isThrownBy(() -> assertThat(predicate).rejects(expectedValue)).withMessage(shouldNotAccept(wrapPredicate,expectedValue,PredicateDescription.GIVEN).create());
}
