@Test public void should_fail_if_completable_future_is_incomplete(){
  CompletableFuture<String> future=new CompletableFuture<>();
  assertThatThrownBy(() -> assertThat(future).hasFailedWithThrowableThat()).isInstanceOf(AssertionError.class).hasMessage(shouldHaveFailed(future).create());
}
