@Test public void onCompleteThrowsRuntimeException() throws IOException, InterruptedException {
  doTest("runtime",false);
}
