@Test public void pooledConnectionFound() throws IOException {
  server.enqueue(new MockResponse());
  server.enqueue(new MockResponse());
  Call call1=client.newCall(new Request.Builder().url(server.url("/")).build());
  Response response1=call1.execute();
  assertEquals(200,response1.code());
  response1.body().close();
  ConnectionAcquired connectionAcquired1=listener.removeUpToEvent(ConnectionAcquired.class);
  listener.clearAllEvents();
  Call call2=client.newCall(new Request.Builder().url(server.url("/")).build());
  Response response2=call2.execute();
  assertEquals(200,response2.code());
  response2.body().close();
  ConnectionAcquired connectionAcquired2=listener.removeUpToEvent(ConnectionAcquired.class);
  assertSame(connectionAcquired1.connection,connectionAcquired2.connection);
}
