@Test public void should_throw_error_wrapping_catched_IOException() throws IOException {
  IOException cause=new IOException();
  when(diff.diff(actual,defaultCharset(),expected,defaultCharset())).thenThrow(cause);
  assertThatExceptionOfType(UncheckedIOException.class).isThrownBy(() -> files.assertSameContentAs(someInfo(),actual,defaultCharset(),expected,defaultCharset())).withCause(cause);
}
