@Test public void timeoutsUpdatedOnReusedConnections() throws Exception {
  server.enqueue(new MockResponse().setBody("abc"));
  server.enqueue(new MockResponse().setBody("def").throttleBody(1,750,TimeUnit.MILLISECONDS));
  client=client.newBuilder().readTimeout(1000,TimeUnit.MILLISECONDS).build();
  executeSynchronously("/a").assertBody("abc");
  client=client.newBuilder().readTimeout(250,TimeUnit.MILLISECONDS).build();
  Request request=new Request.Builder().url(server.url("/b")).build();
  Response response=client.newCall(request).execute();
  BufferedSource bodySource=response.body().source();
  assertEquals('d',bodySource.readByte());
  long startNanos=System.nanoTime();
  try {
    bodySource.readByte();
    fail();
  }
 catch (  IOException expected) {
    long elapsedNanos=System.nanoTime() - startNanos;
    long elapsedMillis=TimeUnit.NANOSECONDS.toMillis(elapsedNanos);
    assertTrue(Util.format("Timed out: %sms",elapsedMillis),elapsedMillis < 500);
  }
 finally {
    bodySource.close();
  }
}
